/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import javax.swing.JOptionPane;

/**
 *
 * @author t.combarieu
 */
public class AjoutDialog extends javax.swing.JDialog {

    private PropertyChangeSupport listeners = new PropertyChangeSupport(this);

    public void addPropertyChangeListener(PropertyChangeListener l) {
        this.listeners.addPropertyChangeListener(l);
    }

    /**
     * Creates new form AjoutDialog
     */
    public AjoutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JAjouter = new javax.swing.JButton();
        jTextNom = new javax.swing.JTextField();
        JNom = new javax.swing.JLabel();
        jPrenom = new javax.swing.JLabel();
        jIdentifiant = new javax.swing.JLabel();
        JTextPrenom = new javax.swing.JTextField();
        jPassword = new javax.swing.JLabel();
        jTextIdentifiant = new javax.swing.JPasswordField();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        boutonDeMaskPassword = new javax.swing.JButton();
        boutonDeMaskIdentifiant1 = new javax.swing.JButton();
        jTextMail = new javax.swing.JTextField();
        jTextPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JAjouter.setText("Ajouter");
        JAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAjouterActionPerformed(evt);
            }
        });

        jTextNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomActionPerformed(evt);
            }
        });

        JNom.setText("Nom :");

        jPrenom.setText("Prenom :");

        jIdentifiant.setText("Identifiant : ");

        JTextPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextPrenomActionPerformed(evt);
            }
        });

        jPassword.setText("Mot de passe :");

        jTextIdentifiant.setToolTipText("");
        jTextIdentifiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdentifiantActionPerformed(evt);
            }
        });

        cancelButton.setText("Annuler");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Adresse Mail :");

        boutonDeMaskPassword.setText("boutonDeMaskPassword");
        boutonDeMaskPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonDeMaskPasswordActionPerformed(evt);
            }
        });

        boutonDeMaskIdentifiant1.setText("boutonDeMaskIdentifiant");
        boutonDeMaskIdentifiant1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonDeMaskIdentifiant1ActionPerformed(evt);
            }
        });

        jTextMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMailActionPerformed(evt);
            }
        });

        jTextPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPassword)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jPrenom)
                                .addComponent(JNom)
                                .addComponent(jIdentifiant)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(JTextPrenom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(jTextNom, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextIdentifiant, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextMail)
                            .addComponent(jTextPassword, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boutonDeMaskPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boutonDeMaskIdentifiant1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(JAjouter)
                        .addGap(43, 43, 43)
                        .addComponent(cancelButton)))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNom))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPrenom)
                    .addComponent(JTextPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jIdentifiant)
                    .addComponent(boutonDeMaskIdentifiant1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPassword)
                    .addComponent(boutonDeMaskPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JAjouter)
                    .addComponent(cancelButton))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomActionPerformed

    private void JAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAjouterActionPerformed
        String textPrenom = this.getPrenom();
        String textNom = this.getNom();
        String textEmail = this.getEmail();
        String textIdentifiant = this.getIdentifiant();
        String textPassword = this.getPassword();

        String regexNomPrenom = "^[A-Z][a-zéèêëàâäïîç\\-']{1,}$";
        String regexEmail = "^[\\w.-]+@[\\w.-]+\\.\\w{2,}$";
        String regexIdentifiant = "^[a-zA-Z0-9]{4,15}$";
        String regexMotDePasse = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d).{8,}$";

        if (textPrenom.isEmpty() && textNom.isEmpty() && textEmail.isEmpty() && textIdentifiant.isEmpty() && textPassword.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs de saisie");
            return;

        } else if (textPrenom.isEmpty() || textNom.isEmpty() || textEmail.isEmpty() || textIdentifiant.isEmpty() || textPassword.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vous avez oublié de renseigner une de vos informations");
            return;
            
        } else if (!textNom.matches(regexNomPrenom) && textNom.length() < 2 ) {
            JOptionPane.showMessageDialog(null, "Nom invalide. Il doit commencer par une majuscule et ne contenir que des lettres.");
            return;
        }
        
         else if(!textPrenom.matches(regexNomPrenom) && textNom.length() < 2 ) {
            JOptionPane.showMessageDialog(null, "Prénom invalide. Il doit commencer par une majuscule et ne contenir que des lettres.");
            return;
        }
        
        else if (!textEmail.matches(regexEmail)) {
            JOptionPane.showMessageDialog(null, "Email invalide. Format attendu : exemple@domaine.com");
            return;
        }

        else if (!textIdentifiant.matches(regexIdentifiant)) {
                JOptionPane.showMessageDialog(null, "Identifiant invalide. Il doit être alphanumérique (4 à 15 caractères).");
                return;
            }

        else if (!textPassword.matches(regexMotDePasse)) {
                JOptionPane.showMessageDialog(null, "Mot de passe invalide. Il doit contenir au moins 8 caractères, une majuscule, une minuscule et un chiffre.");
                return;
            }

            listeners.firePropertyChange("validNewUser", null, null);

            // Récpérer la valeurs des champs
            //String nom = jTextNom.getText();
            //String prenom = JTextPrenom.getText();
            //String mail = jMail.getText();
            //String identifiant = JTextIdentifiant.getText();
            //String password = jTextPassword.getText();

    }//GEN-LAST:event_JAjouterActionPerformed

    private void jTextIdentifiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdentifiantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIdentifiantActionPerformed

    private void JTextPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextPrenomActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void boutonDeMaskPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonDeMaskPasswordActionPerformed
        
    }//GEN-LAST:event_boutonDeMaskPasswordActionPerformed

    private void boutonDeMaskIdentifiant1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonDeMaskIdentifiant1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonDeMaskIdentifiant1ActionPerformed

    private void jTextMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMailActionPerformed

    private void jTextPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AjoutDialog dialog = new AjoutDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JAjouter;
    private javax.swing.JLabel JNom;
    private javax.swing.JTextField JTextPrenom;
    private javax.swing.JButton boutonDeMaskIdentifiant1;
    private javax.swing.JButton boutonDeMaskPassword;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jIdentifiant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jPassword;
    private javax.swing.JLabel jPrenom;
    private javax.swing.JPasswordField jTextIdentifiant;
    private javax.swing.JTextField jTextMail;
    private javax.swing.JTextField jTextNom;
    private javax.swing.JPasswordField jTextPassword;
    // End of variables declaration//GEN-END:variables

    public String getNom() {
        return this.jTextNom.getText();
    }

    public String getPrenom() {
        return this.JTextPrenom.getText();
    }

    public String getEmail() {
        return this.jTextIdentifiant.getText();
    }

    public String getIdentifiant() {
        return this.jTextIdentifiant.getText();
    }

    public String getPassword() {
        return this.jTextIdentifiant.getText();
    }

    public void setDefaultTextfieldData() {
        this.jTextNom.setText("");
        this.JTextPrenom.setText("");
        this.jTextIdentifiant.setText("");
        this.jTextIdentifiant.setText("");
        this.jTextIdentifiant.setText("");

    }
}
